#if defined(_MSC_VER)
#  pragma warning(disable: 4295) // "array is too small to include a terminating null character"
#endif

const char decoded_ACGT[256 * 4] =
{
  "AAAA" "CAAA" "GAAA" "TAAA"
  "ACAA" "CCAA" "GCAA" "TCAA"
  "AGAA" "CGAA" "GGAA" "TGAA"
  "ATAA" "CTAA" "GTAA" "TTAA"
  "AACA" "CACA" "GACA" "TACA"
  "ACCA" "CCCA" "GCCA" "TCCA"
  "AGCA" "CGCA" "GGCA" "TGCA"
  "ATCA" "CTCA" "GTCA" "TTCA"
  "AAGA" "CAGA" "GAGA" "TAGA"
  "ACGA" "CCGA" "GCGA" "TCGA"
  "AGGA" "CGGA" "GGGA" "TGGA"
  "ATGA" "CTGA" "GTGA" "TTGA"
  "AATA" "CATA" "GATA" "TATA"
  "ACTA" "CCTA" "GCTA" "TCTA"
  "AGTA" "CGTA" "GGTA" "TGTA"
  "ATTA" "CTTA" "GTTA" "TTTA"

  "AAAC" "CAAC" "GAAC" "TAAC"
  "ACAC" "CCAC" "GCAC" "TCAC"
  "AGAC" "CGAC" "GGAC" "TGAC"
  "ATAC" "CTAC" "GTAC" "TTAC"
  "AACC" "CACC" "GACC" "TACC"
  "ACCC" "CCCC" "GCCC" "TCCC"
  "AGCC" "CGCC" "GGCC" "TGCC"
  "ATCC" "CTCC" "GTCC" "TTCC"
  "AAGC" "CAGC" "GAGC" "TAGC"
  "ACGC" "CCGC" "GCGC" "TCGC"
  "AGGC" "CGGC" "GGGC" "TGGC"
  "ATGC" "CTGC" "GTGC" "TTGC"
  "AATC" "CATC" "GATC" "TATC"
  "ACTC" "CCTC" "GCTC" "TCTC"
  "AGTC" "CGTC" "GGTC" "TGTC"
  "ATTC" "CTTC" "GTTC" "TTTC"

  "AAAG" "CAAG" "GAAG" "TAAG"
  "ACAG" "CCAG" "GCAG" "TCAG"
  "AGAG" "CGAG" "GGAG" "TGAG"
  "ATAG" "CTAG" "GTAG" "TTAG"
  "AACG" "CACG" "GACG" "TACG"
  "ACCG" "CCCG" "GCCG" "TCCG"
  "AGCG" "CGCG" "GGCG" "TGCG"
  "ATCG" "CTCG" "GTCG" "TTCG"
  "AAGG" "CAGG" "GAGG" "TAGG"
  "ACGG" "CCGG" "GCGG" "TCGG"
  "AGGG" "CGGG" "GGGG" "TGGG"
  "ATGG" "CTGG" "GTGG" "TTGG"
  "AATG" "CATG" "GATG" "TATG"
  "ACTG" "CCTG" "GCTG" "TCTG"
  "AGTG" "CGTG" "GGTG" "TGTG"
  "ATTG" "CTTG" "GTTG" "TTTG"

  "AAAT" "CAAT" "GAAT" "TAAT"
  "ACAT" "CCAT" "GCAT" "TCAT"
  "AGAT" "CGAT" "GGAT" "TGAT"
  "ATAT" "CTAT" "GTAT" "TTAT"
  "AACT" "CACT" "GACT" "TACT"
  "ACCT" "CCCT" "GCCT" "TCCT"
  "AGCT" "CGCT" "GGCT" "TGCT"
  "ATCT" "CTCT" "GTCT" "TTCT"
  "AAGT" "CAGT" "GAGT" "TAGT"
  "ACGT" "CCGT" "GCGT" "TCGT"
  "AGGT" "CGGT" "GGGT" "TGGT"
  "ATGT" "CTGT" "GTGT" "TTGT"
  "AATT" "CATT" "GATT" "TATT"
  "ACTT" "CCTT" "GCTT" "TCTT"
  "AGTT" "CGTT" "GGTT" "TGTT"
  "ATTT" "CTTT" "GTTT" "TTTT"
};


const char decoded_acgt[256 * 4] =
{
  "aaaa" "caaa" "gaaa" "taaa"
  "acaa" "ccaa" "gcaa" "tcaa"
  "agaa" "cgaa" "ggaa" "tgaa"
  "ataa" "ctaa" "gtaa" "ttaa"
  "aaca" "caca" "gaca" "taca"
  "acca" "ccca" "gcca" "tcca"
  "agca" "cgca" "ggca" "tgca"
  "atca" "ctca" "gtca" "ttca"
  "aaga" "caga" "gaga" "taga"
  "acga" "ccga" "gcga" "tcga"
  "agga" "cgga" "ggga" "tgga"
  "atga" "ctga" "gtga" "ttga"
  "aata" "cata" "gata" "tata"
  "acta" "ccta" "gcta" "tcta"
  "agta" "cgta" "ggta" "tgta"
  "atta" "ctta" "gtta" "ttta"

  "aaac" "caac" "gaac" "taac"
  "acac" "ccac" "gcac" "tcac"
  "agac" "cgac" "ggac" "tgac"
  "atac" "ctac" "gtac" "ttac"
  "aacc" "cacc" "gacc" "tacc"
  "accc" "cccc" "gccc" "tccc"
  "agcc" "cgcc" "ggcc" "tgcc"
  "atcc" "ctcc" "gtcc" "ttcc"
  "aagc" "cagc" "gagc" "tagc"
  "acgc" "ccgc" "gcgc" "tcgc"
  "aggc" "cggc" "gggc" "tggc"
  "atgc" "ctgc" "gtgc" "ttgc"
  "aatc" "catc" "gatc" "tatc"
  "actc" "cctc" "gctc" "tctc"
  "agtc" "cgtc" "ggtc" "tgtc"
  "attc" "cttc" "gttc" "tttc"

  "aaag" "caag" "gaag" "taag"
  "acag" "ccag" "gcag" "tcag"
  "agag" "cgag" "ggag" "tgag"
  "atag" "ctag" "gtag" "ttag"
  "aacg" "cacg" "gacg" "tacg"
  "accg" "cccg" "gccg" "tccg"
  "agcg" "cgcg" "ggcg" "tgcg"
  "atcg" "ctcg" "gtcg" "ttcg"
  "aagg" "cagg" "gagg" "tagg"
  "acgg" "ccgg" "gcgg" "tcgg"
  "aggg" "cggg" "gggg" "tggg"
  "atgg" "ctgg" "gtgg" "ttgg"
  "aatg" "catg" "gatg" "tatg"
  "actg" "cctg" "gctg" "tctg"
  "agtg" "cgtg" "ggtg" "tgtg"
  "attg" "cttg" "gttg" "tttg"

  "aaat" "caat" "gaat" "taat"
  "acat" "ccat" "gcat" "tcat"
  "agat" "cgat" "ggat" "tgat"
  "atat" "ctat" "gtat" "ttat"
  "aact" "cact" "gact" "tact"
  "acct" "ccct" "gcct" "tcct"
  "agct" "cgct" "ggct" "tgct"
  "atct" "ctct" "gtct" "ttct"
  "aagt" "cagt" "gagt" "tagt"
  "acgt" "ccgt" "gcgt" "tcgt"
  "aggt" "cggt" "gggt" "tggt"
  "atgt" "ctgt" "gtgt" "ttgt"
  "aatt" "catt" "gatt" "tatt"
  "actt" "cctt" "gctt" "tctt"
  "agtt" "cgtt" "ggtt" "tgtt"
  "attt" "cttt" "gttt" "tttt"
};


const char decoded_ACGU[256 * 4] =
{
  "AAAA" "CAAA" "GAAA" "UAAA"
  "ACAA" "CCAA" "GCAA" "UCAA"
  "AGAA" "CGAA" "GGAA" "UGAA"
  "AUAA" "CUAA" "GUAA" "UUAA"
  "AACA" "CACA" "GACA" "UACA"
  "ACCA" "CCCA" "GCCA" "UCCA"
  "AGCA" "CGCA" "GGCA" "UGCA"
  "AUCA" "CUCA" "GUCA" "UUCA"
  "AAGA" "CAGA" "GAGA" "UAGA"
  "ACGA" "CCGA" "GCGA" "UCGA"
  "AGGA" "CGGA" "GGGA" "UGGA"
  "AUGA" "CUGA" "GUGA" "UUGA"
  "AAUA" "CAUA" "GAUA" "UAUA"
  "ACUA" "CCUA" "GCUA" "UCUA"
  "AGUA" "CGUA" "GGUA" "UGUA"
  "AUUA" "CUUA" "GUUA" "UUUA"

  "AAAC" "CAAC" "GAAC" "UAAC"
  "ACAC" "CCAC" "GCAC" "UCAC"
  "AGAC" "CGAC" "GGAC" "UGAC"
  "AUAC" "CUAC" "GUAC" "UUAC"
  "AACC" "CACC" "GACC" "UACC"
  "ACCC" "CCCC" "GCCC" "UCCC"
  "AGCC" "CGCC" "GGCC" "UGCC"
  "AUCC" "CUCC" "GUCC" "UUCC"
  "AAGC" "CAGC" "GAGC" "UAGC"
  "ACGC" "CCGC" "GCGC" "UCGC"
  "AGGC" "CGGC" "GGGC" "UGGC"
  "AUGC" "CUGC" "GUGC" "UUGC"
  "AAUC" "CAUC" "GAUC" "UAUC"
  "ACUC" "CCUC" "GCUC" "UCUC"
  "AGUC" "CGUC" "GGUC" "UGUC"
  "AUUC" "CUUC" "GUUC" "UUUC"

  "AAAG" "CAAG" "GAAG" "UAAG"
  "ACAG" "CCAG" "GCAG" "UCAG"
  "AGAG" "CGAG" "GGAG" "UGAG"
  "AUAG" "CUAG" "GUAG" "UUAG"
  "AACG" "CACG" "GACG" "UACG"
  "ACCG" "CCCG" "GCCG" "UCCG"
  "AGCG" "CGCG" "GGCG" "UGCG"
  "AUCG" "CUCG" "GUCG" "UUCG"
  "AAGG" "CAGG" "GAGG" "UAGG"
  "ACGG" "CCGG" "GCGG" "UCGG"
  "AGGG" "CGGG" "GGGG" "UGGG"
  "AUGG" "CUGG" "GUGG" "UUGG"
  "AAUG" "CAUG" "GAUG" "UAUG"
  "ACUG" "CCUG" "GCUG" "UCUG"
  "AGUG" "CGUG" "GGUG" "UGUG"
  "AUUG" "CUUG" "GUUG" "UUUG"

  "AAAU" "CAAU" "GAAU" "UAAU"
  "ACAU" "CCAU" "GCAU" "UCAU"
  "AGAU" "CGAU" "GGAU" "UGAU"
  "AUAU" "CUAU" "GUAU" "UUAU"
  "AACU" "CACU" "GACU" "UACU"
  "ACCU" "CCCU" "GCCU" "UCCU"
  "AGCU" "CGCU" "GGCU" "UGCU"
  "AUCU" "CUCU" "GUCU" "UUCU"
  "AAGU" "CAGU" "GAGU" "UAGU"
  "ACGU" "CCGU" "GCGU" "UCGU"
  "AGGU" "CGGU" "GGGU" "UGGU"
  "AUGU" "CUGU" "GUGU" "UUGU"
  "AAUU" "CAUU" "GAUU" "UAUU"
  "ACUU" "CCUU" "GCUU" "UCUU"
  "AGUU" "CGUU" "GGUU" "UGUU"
  "AUUU" "CUUU" "GUUU" "UUUU"
};


const char decoded_acgu[256 * 4] =
{
  "aaaa" "caaa" "gaaa" "uaaa"
  "acaa" "ccaa" "gcaa" "ucaa"
  "agaa" "cgaa" "ggaa" "ugaa"
  "auaa" "cuaa" "guaa" "uuaa"
  "aaca" "caca" "gaca" "uaca"
  "acca" "ccca" "gcca" "ucca"
  "agca" "cgca" "ggca" "ugca"
  "auca" "cuca" "guca" "uuca"
  "aaga" "caga" "gaga" "uaga"
  "acga" "ccga" "gcga" "ucga"
  "agga" "cgga" "ggga" "ugga"
  "auga" "cuga" "guga" "uuga"
  "aaua" "caua" "gaua" "uaua"
  "acua" "ccua" "gcua" "ucua"
  "agua" "cgua" "ggua" "ugua"
  "auua" "cuua" "guua" "uuua"

  "aaac" "caac" "gaac" "uaac"
  "acac" "ccac" "gcac" "ucac"
  "agac" "cgac" "ggac" "ugac"
  "auac" "cuac" "guac" "uuac"
  "aacc" "cacc" "gacc" "uacc"
  "accc" "cccc" "gccc" "uccc"
  "agcc" "cgcc" "ggcc" "ugcc"
  "aucc" "cucc" "gucc" "uucc"
  "aagc" "cagc" "gagc" "uagc"
  "acgc" "ccgc" "gcgc" "ucgc"
  "aggc" "cggc" "gggc" "uggc"
  "augc" "cugc" "gugc" "uugc"
  "aauc" "cauc" "gauc" "uauc"
  "acuc" "ccuc" "gcuc" "ucuc"
  "aguc" "cguc" "gguc" "uguc"
  "auuc" "cuuc" "guuc" "uuuc"

  "aaag" "caag" "gaag" "uaag"
  "acag" "ccag" "gcag" "ucag"
  "agag" "cgag" "ggag" "ugag"
  "auag" "cuag" "guag" "uuag"
  "aacg" "cacg" "gacg" "uacg"
  "accg" "cccg" "gccg" "uccg"
  "agcg" "cgcg" "ggcg" "ugcg"
  "aucg" "cucg" "gucg" "uucg"
  "aagg" "cagg" "gagg" "uagg"
  "acgg" "ccgg" "gcgg" "ucgg"
  "aggg" "cggg" "gggg" "uggg"
  "augg" "cugg" "gugg" "uugg"
  "aaug" "caug" "gaug" "uaug"
  "acug" "ccug" "gcug" "ucug"
  "agug" "cgug" "ggug" "ugug"
  "auug" "cuug" "guug" "uuug"

  "aaau" "caau" "gaau" "uaau"
  "acau" "ccau" "gcau" "ucau"
  "agau" "cgau" "ggau" "ugau"
  "auau" "cuau" "guau" "uuau"
  "aacu" "cacu" "gacu" "uacu"
  "accu" "cccu" "gccu" "uccu"
  "agcu" "cgcu" "ggcu" "ugcu"
  "aucu" "cucu" "gucu" "uucu"
  "aagu" "cagu" "gagu" "uagu"
  "acgu" "ccgu" "gcgu" "ucgu"
  "aggu" "cggu" "gggu" "uggu"
  "augu" "cugu" "gugu" "uugu"
  "aauu" "cauu" "gauu" "uauu"
  "acuu" "ccuu" "gcuu" "ucuu"
  "aguu" "cguu" "gguu" "uguu"
  "auuu" "cuuu" "guuu" "uuuu"
};

#if defined(_MSC_VER)
#  pragma warning(default: 4295) // "array is too small to include a terminating null character"
#endif